apiVersion: ENC[AES256_GCM,data:qKs=,iv:tFm77bfr2KUVVHOkeMIKkW7Cz5Kz7/fkSnAUhLkJnk8=,tag:ilLl0Y1oR90b9+P/ZV02ZQ==,type:str]
kind: ENC[AES256_GCM,data:pS+LbYmw,iv:5tw1FatZV4zBPovwhAoUVxeUSWd0sfJ1KKUbvNhWDgw=,tag:6W6mBCs5QlTJQZjNBo/kcg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/9OtxF1GfNJXTOvchtMXlcwMQg==,iv:Pfk6oGJ/PHcONu/9vurkMJsh4IbXGWnvYyAZQmhahIs=,tag:YbJ1ou3F97r194snTHUR6Q==,type:str]
    namespace: ENC[AES256_GCM,data:gdHxr1bTpQ==,iv:wl1YoMs17wcMuCQXS+IPWJt/0SrCU7u4FEitd5iJ3kI=,tag:8k93U9Ifov29wz17tJlDnA==,type:str]
type: ENC[AES256_GCM,data:lUrjDwTg,iv:RlOLGTYIQ6san47+2NdH56G+HRKTY13kFSr7dWmaMqI=,tag:y9hSPUPd6aCcOeYLQh1XsQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:pxgU10rPrQucaP4uQ6o=,iv:ZcDzIkeBzlBP/qWvqxqHNgEGPkChMYN3qzZMuDhSOn8=,tag:Dq1MaSj/2CZEVGgDVfvrJw==,type:comment]
    NODE_BACKEND_PREFIX: ENC[AES256_GCM,data:jwXDxQ==,iv:Xa5roVAzhjToIPILnQvlZEk5B2Cn8f8yuiIqdU05FwA=,tag:QqPQbfABjFttR9m1P0L9Rw==,type:str]
    #ENC[AES256_GCM,data:+tvLZIuM0dIDHfOG,iv:0cqRa8WIjMDqc2IegmNOcY+Bmv7EsRR7qPn0UkAYUbk=,tag:ROYd7rwS3G9CGxEtaDtduQ==,type:comment]
    NODE_APP_DATABASE_PORT: ENC[AES256_GCM,data:bkRF8w==,iv:mVEuWxhbUKe7NVmSPjhHV75b91+71GV05p4js5SIJQE=,tag:RFMpGW7hsbQ9oXWkVIFX9A==,type:str]
    NODE_APP_DATABASE_NAME: ENC[AES256_GCM,data:TmV8gS0tnGJn,iv:m3jmtf+/kmJcxHWsJYhBgfPhWcUW9NbBYUuXVETAWBs=,tag:6SJAD4ASoXsGo3Tqe7XWiA==,type:str]
    NODE_APP_DATABASE_USER: ENC[AES256_GCM,data:wEHdmAcPFiAVfiOumg==,iv:9UlXXMJNxr/luCtwf1tzwviWeqIiNvAx5AmIGznZCXc=,tag:Tar6acar7Smvtxgil4KV4Q==,type:str]
    NODE_APP_DATABASE_PASSWORD: ENC[AES256_GCM,data:qEjMF+gS5gLMyLH17I89TQIw,iv:PHRjs2Ne8omCF/3mqRlju9IRuADcwVewawObZ0WzM1Q=,tag:iHgNZhmIQ3VimlmcOaqwwg==,type:str]
    #ENC[AES256_GCM,data:dg6BiZLQzBe70edpaVjc,iv:/VxMyaHydu63LrVLuh/MWaPgeHXMBYe7R8oeAuR5RZw=,tag:1Oez0auwhqnUKYZS1mCmLA==,type:comment]
    NODE_APP_REDIS_URL: ENC[AES256_GCM,data:gKFukpc7zn+lBf7ZOYRsJwzqYBzdPCo=,iv:aEU9+x9j4oPrupjSPJD03bU++BDfHiqi/YBICa+107k=,tag:nYZdSXKVVZvy6qitGSNK7Q==,type:str]
    NODE_APP_REDIS_PASSWORD: ENC[AES256_GCM,data:9WaYRCll5eNWdtvXN8AXzN1bM2o=,iv:SCTzaEPfipXqWC6sgHpSrRGkIlU83X7ruf+qWsunIiE=,tag:R6y6tgblFKKkMtCxPEfYSw==,type:str]
    #ENC[AES256_GCM,data:Czz5Q7+Tfheo2Is=,iv:jgdxEWtIdZxR/lE6BXvUmgkxDjaaqN9VKawaDJAzfIE=,tag:XorA7zDJ03KR07PGLSD9UQ==,type:comment]
    NODE_APP_KAFKA_CLIENT_ID: ENC[AES256_GCM,data:Yoj4jKu5d7x85OUT,iv:5vIINg6ZcJQxsLQBkAF7D70UJgQW+dyhJdmb4A2Lc6Q=,tag:Ta+PWuPFf0SEsycVYIpVLQ==,type:str]
    NODE_APP_KAFKA_GROUP_ID: ENC[AES256_GCM,data:CcBx8TStua/L0fo8,iv:mUk30nTfRdoQlBlGmiD8oy8v8pU8LH2MCoV0BxTH4l0=,tag:a8ow42Avzr3+DF+6fpN5YQ==,type:str]
    NODE_APP_KAFKA_SASL_USERNAME: ENC[AES256_GCM,data:u5CE+1LyCvH2,iv:HKISVaCvW4Wxft7t2g8JoNi10E2CJ5jECnNeWeMnrTg=,tag:dCt7wCnPgdMxh9ulkjiszQ==,type:str]
    NODE_APP_KAFKA_SASL_PASSWORD: ENC[AES256_GCM,data:yI+rRyWsXI3UtdoxSLDtFttz3KrO9wc9P4TvFg==,iv:efXg5HJpSNWQyXCuqdZBGKDMRjqwv2pRomDa7jik8f8=,tag:PULT6zTyKYgKMsJZpd71ZA==,type:str]
    NODE_APP_KAFKA_SASL_MECHANISM: ENC[AES256_GCM,data:UpQFgBfLM15jSEt6RA==,iv:p/neV6hiFd0gzBubkQ/IfTF9o4BG2oARLpdXdjUffPc=,tag:U+KF4TRTD3o7jRKMlwOD9g==,type:str]
    NODE_APP_KAFKA_SSL: ENC[AES256_GCM,data:bTmFq9g=,iv:/2OlfHJkuJMScahFWzsNi1YYeaesHksZFvehPhlmjeU=,tag:FXSu8pxjMIzo/1ErmvJeXw==,type:str]
    #ENC[AES256_GCM,data:e0SiEknZrzf3Br9yYsr1gKXd3i2Vw6rl6ZcgMgDU+MX5aF7HHN26vonxmAybLFZHm3/oXbaKp+r6U1DfIVjvBd1TDj9wT7S5KQ8vanaWZ4rIsQ/ZKuZsCkGxVjBIZfDiENiDPdDBIgw7WVvptOrBZExJSTF0rAhhOG2toHk=,iv:9fSkm8rjG01XAvGWe5qaRuhazZF3qyutbrUWEou6r5M=,tag:xO2O/bATfp5NN0fGJzcTaQ==,type:comment]
    NODE_APP_TICKET_PUBLIC_JWK: ENC[AES256_GCM,data:zVVHif2IrCh1xSvaeiwQ2GzdBIOJuWzmINg0a+TsyKC+eUlKn3CDO6RoT+XEfLwyZ7doLbxi82pi1xLS06LCOGcgcLL/LW3U3K47WVOKpH+vO9ucxwzeBgmDBmz8IDZYAGHON2dyhOH7Zh+iiC5/3V1O4fRW1ghykRtV0ZVJLJ1arBPLncQCQnO86cuuTNiLeZjAuNqcfBX1YF6lFLQXwOvjga0yJksiA71EjL6Wx3h7hYBriuih5ZA2k+KGU9baTwfM8y168nNPszafJlaLf13e5r5cyzt1a/nVvMND6u2EB7wlL6IPR7oyThAVTsb4i0QhbZkZL4IKozYJ0eHSRL2M6ObySiYl7cEXbyGIjFMurVZcMWRMW/YCFi2X178vJ0LesH8C+JeSedARwk7JmQwljIANTwFygf+LqpTWlvTrtfQUIrGDQ91Hr/qz/cnkaqB3tVr70w8SobINbi3gFLPMIHOdBLALaePvJYcAgCR98dH7aLI1Xqn5SsR2hlj/s1+jvExgix1Y5zIAzvXne/1qe5a1di+tb0QSM+Rjhjv+URXSl9FV1Q12x+QqFnh857hQigxWNmAujgYhXticrmyifuPBrA2o,iv:9hPutAABjDvbduUlFUjmGCMugzYqhFiIBOWfjSpaJzo=,tag:wza0Mqz9VT4uFWhWZjdOjQ==,type:str]
    NODE_APP_TICKET_ISS: ENC[AES256_GCM,data:eBDenFy/vBZgBvIQ,iv:7ikRr2QoDA//Tu/uqsWIgsTNDB9W27M3cYTAXATB+98=,tag:PnJHXIHdBst6WuTrXLJLoA==,type:str]
    NODE_APP_TICKET_AUD: ENC[AES256_GCM,data:fu92P0EUULqt8yOa,iv:c1nYIDBkPGkScD2Em6capArBHiBuCjvhcq1Twt1kXgg=,tag:hzx7vJd886kK38MrmpEk/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n3mp0x8n3gwm5lgrz0mglt9e03su2c2ufvx5xfqmadcpklxt03yqd9mmz8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWkZpVmhVamNzdUptd1Fn
            U0VnS0JiSVJIRTUzc01aK2o1OFluQTRJOUJnCnlYNEZ0bi9NOU1GdWlDNldJdGxa
            bnRzOHZqb05SZ21Ga2hNVDJ0MkVHeGsKLS0tICtYTmNpMXVNVG9ma09JdHpKTi92
            V3lvMmh6N0tqYSs1VUdOYk85Y3BNMFUKwqArd6s7rlLkgJArUlrEqXy9PiKJR0LB
            irgvIqZMGZev2Ha9hyWKv5MnrcJz3+lno+nsfoK/3o6sUUf/T2NdFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:29:07Z"
    mac: ENC[AES256_GCM,data:qbQlrWUFCt2+YN7XegRZSHOAX2B+wFe1wrQaFHucrlLhJGRnxw3+AdPpqyNgk1jUURhdQACDJBkwpwLvgHbSljTI4HhYrqNdWT6hN7UEcSkf7CGqX1+5xip9mZSmV70+hz0jPVsS6NP2fS/eJfKjwrmz2milDzSC/5SgOu+GUe8=,iv:LTtWpSH3F6/0bdOF8zctEI7Sw3215YeewYNsff58CMs=,tag:K6dHEWNQ/olQVu3QQ27tNQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
